# Site settings
title: Bobbys World - Random thoughts about life and design
email: hello@bobbyreyes.io
description: 
baseurl:
url: "http://bobbysworld.me" # the base hostname & protocol for your site
twitter_username: bobbyreys
github_username:      bobbyreys
linkedin_username:    bobbyreys
instagram_username:   bobbyreys
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title
